{% set version = "1.2.0" %}

package:
  name: sphinx-issues
  version: {{ version }}

source:
  fn: sphinx-issues-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sphinx-issues/sphinx-issues-{{ version }}.tar.gz
  md5: 0f40881c9c95c40c6e752abce61882cc

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - sphinx

test:
  imports:
    - sphinx_issues

about:
  home: https://github.com/sloria/sphinx-issues
  license: MIT
  license_file: LICENSE
  summary: "A Sphinx extension for linking to your project's issue tracker"

extra:
  recipe-maintainers:
    - asmeurer
