{% set version = "4.1.0" %}

package:
  name: sphinx-issues
  version: {{ version }}

source:
  fn: sphinx-issues-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sphinx-issues/sphinx_issues-{{ version }}.tar.gz
  md5: 32aa8ad8672baa29fd81c73d8d65a8e3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - sphinx

test:
  imports:
    - sphinx_issues

about:
  home: https://github.com/sloria/sphinx-issues
  license: MIT
  license_file: LICENSE
  summary: "A Sphinx extension for linking to your project's issue tracker"

extra:
  recipe-maintainers:
    - asmeurer
