{% set name = "sphinx-issues" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name.replace("-", "_") }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 192e43cf071ed7aead401cd14fd15076ecb0866238c095d672180618740c6bae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core <4
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - sphinx

test:
  imports:
    - sphinx_issues
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sloria/sphinx-issues
  summary: "A Sphinx extension for linking to your project's issue tracker"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/sloria/sphinx-issues

extra:
  recipe-maintainers:
    - asmeurer
