{% set name = "sphinx-issues" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace("-", "_") }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 6da131d4545af00be4b48ec7c4086ea82c1371a05116bbe5779f57cff34bf16a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - flit-core <4
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sphinx

test:
  imports:
    - sphinx_issues
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/sloria/sphinx-issues
  summary: "A Sphinx extension for linking to your project's issue tracker"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/sloria/sphinx-issues

extra:
  recipe-maintainers:
    - asmeurer
    - m-rossi
    - zaneselvans
