{% set version = "0.4.0" %}

package:
  name: sphinx-issues
  version: {{ version }}

source:
  fn: sphinx-issues-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sphinx-issues/sphinx-issues-{{ version }}.tar.gz
  md5: c9a9057be12dfc48507fbadc385dada2

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - sphinx

test:
  imports:
    - sphinx_issues

about:
  home: https://github.com/sloria/sphinx-issues
  license: MIT
  license_file: LICENSE
  summary: "A Sphinx extension for linking to your project's issue tracker"

extra:
  recipe-maintainers:
    - asmeurer
