travis:
  secure:
    BINSTAR_TOKEN: hE5atdai5e4OlrRaUjUvXi/EGXI7hT6MuupLr8/l6azwFBVzvQ53ZnY0AJccfTq7iICa362G6oBxkuhVpgcwed37GwcdDhQYO0OGfLXO+Ul7YsDh4mZbMf1KermOhaVItpTzThDKwmYLB0i21M8C3n9iYximF566E48DZq/gtBZTUTMrDT8XpwYfIn4nlvjqXTwOX5gqiuI/6sU7X7q+rbuhXjh/WLEEGCb0ZX6eJpu3PyFe68T9YCqAck9iO8eZLi+RGQ2hb4RIeiBVQEBXYVG7BA/5D2LwAjLthWkz/Z9iUftkTdU6w+Sj/AtiP9th3PQri1sQhsoL94xyA+oAiuc7ci9Bpl6u2qexmWe9B5y2ZwchtvZ2Jct2TgSkWKtH0ZllA6e4Zl6Pyvv73lEh8RbazjJb4WmzISU//EZURIl/m6yA8xNDit9nGBbssYmaUZeDCJUmY5Xl9ueyvAkxYnAls8hCLvpdjLk8SiANaSH1x7kNayyli1NM+Np+Dv5ba21+gumvSVGAh17gYax5w/gfYlzRnjxxhsI+6zfBhJrScs/wBLvS3UTsIKrxijNBm1Hv4IZHJT/AFeaJZLoQOQ6FJQPkArxLtShk4eYSoXSm7j7Tpf40hg22kcHE0s1kkZPUPjRP0Bau+ghXF3cIzZLNGldCY+gDlBD1DUXFaEE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
