travis:
  secure:
    BINSTAR_TOKEN: J47aG5JMrYptjbQHVxxgED61AqDG1oIQhCpTgOAis60c3EA5qnNVPLIoQrpr9ugoaD8VEZmXzRjzjdKyGfkCTugjJLrrY6xRz/y7XPxKdiL0RtXj6O5fCaJXAwto2G8v8Q0RXX39USTsKmNDTq+Adst91T5AAEkxi4c+JLAiAZOea5ImWQeqJ8ha9tiqZzNFbH1zYU9fNd40ciC465G75yZ1Q/6FlJiFH2Va+X4gOU8TtDC40Gsn4lHLjN+O7CgU4W0iKzDJwc3EcAbxDlEJKVuYN69nb/uIclFJJ3j3Kvr5vmsjt6oObMwQyzvvUd1AXPe1iOy4/aGJjK9Rfolu8BGvNW+YP/pYzRvXBhIQbMIM17dlsLNAFbiMFT1YFnnqpy/ihuDLgaG5TNThVNoYm/IRplsHtWS6BevW09O4tb0LDXtG4WOEvV2gSriXxJEI6yOQe+kCjNZUnBWmhD4po2uVlQEHsQDXN5NqjN/g/zf4mK8xxSVdligXW7u9DcY8ZWMc3VhvDyPezu1P7LNS2e9iA78eHBvBJ9vFf79FoYrzAnh6PLpssBN8gF8Hxmk21dYXXAzuAHeBbQUy+KQrry3HI+Kxl9UU9mKKQy1Lr/vwZlf11CQCFrd8YKXVvXraUr5H6MtR5qr9rfkDxXTZW6W8J2igQUHYZxSDcjB45vU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
